-- Reviews become one-per-customer-per-product. Earlier demo data was
-- generated by sampling reviewers *with* replacement, so collapse every
-- duplicate pair down to its earliest row before the constraint goes on --
-- otherwise CREATE UNIQUE INDEX fails on existing data.
DELETE FROM "reviews" a
USING "reviews" b
WHERE a."product_id" = b."product_id"
  AND a."user_id" = b."user_id"
  AND (a."created_at", a."id") > (b."created_at", b."id");

-- CreateIndex
CREATE UNIQUE INDEX "reviews_product_id_user_id_key" ON "reviews"("product_id", "user_id");
